mariadb:
  image: mariadb
  tag: "10.11"
  rootPassword: "root"
  database: "full-stack-ecommerce"
  user: "ecommerceapp"
  password: "StrongPa55WorD"
  port: 3306

storage:
  size: 2Gi
  className: longhorn

dbInit:
  enabled: true
  image: lekimtanloc/01-starter-files_db-scripts:v2
  sqlDir: "/init/sql"
  maxRetries: "100"
  username: "root"
  password: "root"
